# Name: Kevin Leander
# ID: 100918906
# https://github.com/docker/docker-nodejs-sample
 
steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/steady-cat-401619/kevin-100918906:$COMMIT_SHA', '.']
 
# Push the Docker image to the artifact registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/steady-cat-401619/kevin-100918906:$COMMIT_SHA']
 
options:
  # Set defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET
  # defaultLogsBucket: 'gs://your-build-logs-bucket' # Replace with your build logs bucket
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'